all: tesoro
tesoro: Bomba.c Bomba.h Tierra.h Tablero.c Tablero.h TreasureFinder.c
	gcc Bomba.c Bomba.h Tierra.h Tablero.c Tablero.h TreasureFinder.c -o tesoro -Wall
run:
	./tesoro
clean:
	rm -f tesoro *.o




